name = "InvariantCausalPrediction"
uuid = "5fe40f08-422b-4ec7-90aa-ba60e31ac74e"
authors = ["Clarman Cruz"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FreqTables = "da1fdf0e-e0ff-5433-a45f-9bb5ff651cb1"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LIBSVM = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
LightGBM = "7acf609c-83a4-11e9-1ffb-b912bcd3b04a"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJLinearModels = "6ee0df7b-362f-4a72-a706-9e79364fb692"
MLJModels = "d491faf4-2d78-11e9-2867-c94bc002c0b7"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
ParallelKMeans = "42b8e9d4-006b-409a-8472-7f34b3fb58af"
PrettyPrinting = "54e16d92-306c-5ea0-a30b-337be88ac337"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
Queryverse = "612083be-0b0f-5412-89c1-4e7c75506a58"
ShapML = "8523bd24-6f66-414b-9e1e-b02db3916d64"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"
XGBoost = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"

[compat]
julia = "1"
CSV = "^0.7.4"
CategoricalArrays = "^0.8.1"
Clustering = "^0.14.1"
Combinatorics = "^1.0.2"
DataFrames = "^0.21.4"
DecisionTree = "^0.10.7"
Distributions = "^0.23.5"
FreqTables = "^0.4.0"
GLM = "^1.3.9"
Hwloc = "^1.0.3"
HypothesisTests = "^0.10.0"
IJulia = "^1.21.2"
LIBSVM = "^0.4.0"
LightGBM = "^0.3.1"
MLJ = "^0.12.0"
MLJLinearModels = "^0.5.0"
MLJModels = "^0.11.2"
Missings = "^0.4.3"
ParallelKMeans = "^0.1.8"
PrettyPrinting = "^0.2.0"
Query = "^0.12.2"
Queryverse = "^0.6.1"
ShapML = "^0.3.0"
StatsBase = "^0.33.0"
Tables = "^1.0.4"
VegaLite = "^2.2.0"
XGBoost = "^1.1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
